### ISSUE TITLE
导入错误，ImportError: cannot import name 'CLOSED' from 'websockets.connection'

### ISSUE THREAD

**Issue by Fortytwoo** [jiayouzl/python_web_auth#4]
![image](https://user-images.githubusercontent.com/63646555/236110210-e0a55011-cf42-4676-8098-43627e522f7f.png)
请问您的sanic是什么版本的，我根据requirements.txt文件内的版本无法正常运行。

**Comment by jiayouzl** [comment]
pycryptodome==3.15.0
python-dotenv==0.21.0
requests==2.28.1
sanic==22.6.2
sanic_ext==22.6.3
sanic_session==0.8.0
tinydb==4.7.0
Jinja2==3.1.2

各个依赖版本号都在requirements.txt内,这类项目强烈建议在virtualenv,pipenv等虚拟环境下使用,不然就有可能碰到你这样的问题,另外也建议直接使用docker使用,在仓库根目录我也写了[Dockerfile](https://github.com/jiayouzl/python_web_auth/blob/master/Dockerfile)直接构建就行了.

**Comment by jiayouzl** [comment]
解决了已经pull一下即可.

**Comment by Fortytwoo** [comment]
非常感谢，昨天我手动重装了websockets库的10.0版本后它可以正常运行了，我会重新拉取你的库，它完全符合我的需求。
另外建议在md文件内注明demo内的机器码生成函数仅适用于MacOS，它在Windows系统下会导致异常。
以下是我的解决方法：

```
def get_bios_serial_number():
    output = subprocess.check_output("wmic bios get serialnumber").decode().strip()
    serial_number = output.split("\n")[1].strip()
    return serial_number.ljust(16, 'D')


# 获取机器码(MacOS)
def get_serial_number():
    # cmd = "wmic bios get serialnumber"
    # result = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True, check=True)
    # result = get_bios_serial_number()
    return get_bios_serial_number()
```
它会获取Windows系统的机器码并且如果不满足服务端需要的机器码字符数量会补D来满足

**Comment by jiayouzl** [comment]
> 非常感谢，昨天我手动重装了websockets库的10.0版本后它可以正常运行了，我会重新拉取你的库，它完全符合我的需求。 另外建议在md文件内注明demo内的机器码生成函数仅适用于MacOS，它在Windows系统下会导致异常。 以下是我的解决方法：
> 
> ```
> def get_bios_serial_number():
>     output = subprocess.check_output("wmic bios get serialnumber").decode().strip()
>     serial_number = output.split("\n")[1].strip()
>     return serial_number.ljust(16, 'D')
> 
> 
> # 获取机器码(MacOS)
> def get_serial_number():
>     # cmd = "wmic bios get serialnumber"
>     # result = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True, check=True)
>     # result = get_bios_serial_number()
>     return get_bios_serial_number()
> ```
> 
> 它会获取Windows系统的机器码并且如果不满足服务端需要的机器码字符数量会补D来满足

👍🏻
